import tkinter as tk
from tkinter import ttk
from tkinter import simpledialog
import random

# CONSTANTS ----------------------

TXTWIDTH = 10
BG = "snow2"
BG_FACTOR = "light sea green"
BG_DECISION = "chartreuse3"

# TKINTER WINDOW ----------------------

window = tk.Tk()
window.title("PYTHON Decision Matrix")
window.config(padx=50, pady=50, background=BG)

# FUNCTIONS --------------------

def preload(event):
	#Comparing Jobs --> Pay, Location, Benefits, Advancement, Vacation, Holidays, Flexibility, Training, Hours, Security
	#Moving/Relocating --> Cost of Living, City Size, Housing, Traffic, Schools, Safety, Health, Job Prospects, Entertainment, Convenience
	#Buying a Car --> Cost, Safety, Feel, Style, Mileage, Navigation, Space, Depreciation, Add-ons, Warranties
	#Buying a Computer --> Cost, Brand, CPU, HDD, RAM, Graphics Card, OS, Software, Durability, Warranty	
	if cb_w0.get() != "TEMPLATES":
		if cb_w0.get() == "Comparing Jobs":
			btn_factor1.config(text="Pay")
			btn_factor2.config(text="Location")
			btn_factor3.config(text="Benefits")
			btn_factor4.config(text="Advancement")
			btn_factor5.config(text="Vacation")
			btn_factor6.config(text="Holidays")
			btn_factor7.config(text="Flexibility")
			btn_factor8.config(text="Training")
			btn_factor9.config(text="Hours")
			btn_factor10.config(text="Security")
		elif cb_w0.get() == "Moving / Relocating":
			btn_factor1.config(text="Cost of Living")
			btn_factor2.config(text="City Size")
			btn_factor3.config(text="Housing")
			btn_factor4.config(text="Traffic")
			btn_factor5.config(text="Schools")
			btn_factor6.config(text="Safety")
			btn_factor7.config(text="Health")
			btn_factor8.config(text="Job Prospects")
			btn_factor9.config(text="Entertainment")
			btn_factor10.config(text="Convenience")    		
		elif cb_w0.get() == "Buying a Car":
			btn_factor1.config(text="Cost")
			btn_factor2.config(text="Safety")
			btn_factor3.config(text="Feel")
			btn_factor4.config(text="Style")
			btn_factor5.config(text="Mileage")
			btn_factor6.config(text="Navigation")
			btn_factor7.config(text="Space")
			btn_factor8.config(text="Depreciation")
			btn_factor9.config(text="Add-ons")
			btn_factor10.config(text="Warranties")    		
		elif cb_w0.get() == "Buying a Computer":
			btn_factor1.config(text="Cost")
			btn_factor2.config(text="Brand")
			btn_factor3.config(text="CPU")
			btn_factor4.config(text="HDD")
			btn_factor5.config(text="RAM")
			btn_factor6.config(text="Graphics Card")
			btn_factor7.config(text="OS")
			btn_factor8.config(text="Software")
			btn_factor9.config(text="Durability")
			btn_factor10.config(text="Warranty")
		elif cb_w0.get() == "TEST DATA":
			txt_row1_1.delete("0", tk.END)
			txt_row1_2.delete("0", tk.END)
			txt_row1_3.delete("0", tk.END)
			txt_row1_4.delete("0", tk.END)
			txt_row1_5.delete("0", tk.END)
			txt_row1_6.delete("0", tk.END)
			txt_row1_7.delete("0", tk.END)
			txt_row1_8.delete("0", tk.END)
			txt_row1_9.delete("0", tk.END)
			txt_row1_10.delete("0", tk.END)

			txt_row2_1.delete("0", tk.END)
			txt_row2_2.delete("0", tk.END)
			txt_row2_3.delete("0", tk.END)
			txt_row2_4.delete("0", tk.END)
			txt_row2_5.delete("0", tk.END)
			txt_row2_6.delete("0", tk.END)
			txt_row2_7.delete("0", tk.END)
			txt_row2_8.delete("0", tk.END)
			txt_row2_9.delete("0", tk.END)
			txt_row2_10.delete("0", tk.END)

			txt_row3_1.delete("0", tk.END)
			txt_row3_2.delete("0", tk.END)
			txt_row3_3.delete("0", tk.END)
			txt_row3_4.delete("0", tk.END)
			txt_row3_5.delete("0", tk.END)
			txt_row3_6.delete("0", tk.END)
			txt_row3_7.delete("0", tk.END)
			txt_row3_8.delete("0", tk.END)
			txt_row3_9.delete("0", tk.END)
			txt_row3_10.delete("0", tk.END)

			txt_row4_1.delete("0", tk.END)
			txt_row4_2.delete("0", tk.END)
			txt_row4_3.delete("0", tk.END)
			txt_row4_4.delete("0", tk.END)
			txt_row4_5.delete("0", tk.END)
			txt_row4_6.delete("0", tk.END)
			txt_row4_7.delete("0", tk.END)
			txt_row4_8.delete("0", tk.END)
			txt_row4_9.delete("0", tk.END)
			txt_row4_10.delete("0", tk.END)

			txt_row5_1.delete("0", tk.END)
			txt_row5_2.delete("0", tk.END)
			txt_row5_3.delete("0", tk.END)
			txt_row5_4.delete("0", tk.END)
			txt_row5_5.delete("0", tk.END)
			txt_row5_6.delete("0", tk.END)
			txt_row5_7.delete("0", tk.END)
			txt_row5_8.delete("0", tk.END)
			txt_row5_9.delete("0", tk.END)
			txt_row5_10.delete("0", tk.END)

			txt_row6_1.delete("0", tk.END)
			txt_row6_2.delete("0", tk.END)
			txt_row6_3.delete("0", tk.END)
			txt_row6_4.delete("0", tk.END)
			txt_row6_5.delete("0", tk.END)
			txt_row6_6.delete("0", tk.END)
			txt_row6_7.delete("0", tk.END)
			txt_row6_8.delete("0", tk.END)
			txt_row6_9.delete("0", tk.END)
			txt_row6_10.delete("0", tk.END)

			txt_row7_1.delete("0", tk.END)
			txt_row7_2.delete("0", tk.END)
			txt_row7_3.delete("0", tk.END)
			txt_row7_4.delete("0", tk.END)
			txt_row7_5.delete("0", tk.END)
			txt_row7_6.delete("0", tk.END)
			txt_row7_7.delete("0", tk.END)
			txt_row7_8.delete("0", tk.END)
			txt_row7_9.delete("0", tk.END)
			txt_row7_10.delete("0", tk.END)

			txt_row8_1.delete("0", tk.END)
			txt_row8_2.delete("0", tk.END)
			txt_row8_3.delete("0", tk.END)
			txt_row8_4.delete("0", tk.END)
			txt_row8_5.delete("0", tk.END)
			txt_row8_6.delete("0", tk.END)
			txt_row8_7.delete("0", tk.END)
			txt_row8_8.delete("0", tk.END)
			txt_row8_9.delete("0", tk.END)
			txt_row8_10.delete("0", tk.END)

			txt_row9_1.delete("0", tk.END)
			txt_row9_2.delete("0", tk.END)
			txt_row9_3.delete("0", tk.END)
			txt_row9_4.delete("0", tk.END)
			txt_row9_5.delete("0", tk.END)
			txt_row9_6.delete("0", tk.END)
			txt_row9_7.delete("0", tk.END)
			txt_row9_8.delete("0", tk.END)
			txt_row9_9.delete("0", tk.END)
			txt_row9_10.delete("0", tk.END)

			txt_row10_1.delete("0", tk.END)
			txt_row10_2.delete("0", tk.END)
			txt_row10_3.delete("0", tk.END)
			txt_row10_4.delete("0", tk.END)
			txt_row10_5.delete("0", tk.END)
			txt_row10_6.delete("0", tk.END)
			txt_row10_7.delete("0", tk.END)
			txt_row10_8.delete("0", tk.END)
			txt_row10_9.delete("0", tk.END)
			txt_row10_10.delete("0", tk.END)

			txt_row11_t1.delete("0", tk.END)
			txt_row11_t2.delete("0", tk.END)
			txt_row11_t3.delete("0", tk.END)
			txt_row11_t4.delete("0", tk.END)
			txt_row11_t5.delete("0", tk.END)
			txt_row11_t6.delete("0", tk.END)
			txt_row11_t7.delete("0", tk.END)
			txt_row11_t8.delete("0", tk.END)
			txt_row11_t9.delete("0", tk.END)
			txt_row11_t10.delete("0", tk.END)


			txt_row1_1.config(background="white")
			txt_row1_2.config(background="white")
			txt_row1_3.config(background="white")
			txt_row1_4.config(background="white")
			txt_row1_5.config(background="white")
			txt_row1_6.config(background="white")
			txt_row1_7.config(background="white")
			txt_row1_8.config(background="white")
			txt_row1_9.config(background="white")
			txt_row1_10.config(background="white")
			txt_row11_t1.config(background="white")

			txt_row2_1.config(background="white")
			txt_row2_2.config(background="white")
			txt_row2_3.config(background="white")
			txt_row2_4.config(background="white")
			txt_row2_5.config(background="white")
			txt_row2_6.config(background="white")
			txt_row2_7.config(background="white")
			txt_row2_8.config(background="white")
			txt_row2_9.config(background="white")
			txt_row2_10.config(background="white")
			txt_row11_t2.config(background="white")

			txt_row3_1.config(background="white")
			txt_row3_2.config(background="white")
			txt_row3_3.config(background="white")
			txt_row3_4.config(background="white")
			txt_row3_5.config(background="white")
			txt_row3_6.config(background="white")
			txt_row3_7.config(background="white")
			txt_row3_8.config(background="white")
			txt_row3_9.config(background="white")
			txt_row3_10.config(background="white")
			txt_row11_t3.config(background="white")
			
			txt_row4_1.config(background="white")
			txt_row4_2.config(background="white")
			txt_row4_3.config(background="white")
			txt_row4_4.config(background="white")
			txt_row4_5.config(background="white")
			txt_row4_6.config(background="white")
			txt_row4_7.config(background="white")
			txt_row4_8.config(background="white")
			txt_row4_9.config(background="white")
			txt_row4_10.config(background="white")
			txt_row11_t4.config(background="white")

			txt_row5_1.config(background="white")
			txt_row5_2.config(background="white")
			txt_row5_3.config(background="white")
			txt_row5_4.config(background="white")
			txt_row5_5.config(background="white")
			txt_row5_6.config(background="white")
			txt_row5_7.config(background="white")
			txt_row5_8.config(background="white")
			txt_row5_9.config(background="white")
			txt_row5_10.config(background="white")
			txt_row11_t5.config(background="white")
			
			txt_row6_1.config(background="white")
			txt_row6_2.config(background="white")
			txt_row6_3.config(background="white")
			txt_row6_4.config(background="white")
			txt_row6_5.config(background="white")
			txt_row6_6.config(background="white")
			txt_row6_7.config(background="white")
			txt_row6_8.config(background="white")
			txt_row6_9.config(background="white")
			txt_row6_10.config(background="white")
			txt_row11_t6.config(background="white")
			
			txt_row7_1.config(background="white")
			txt_row7_2.config(background="white")
			txt_row7_3.config(background="white")
			txt_row7_4.config(background="white")
			txt_row7_5.config(background="white")
			txt_row7_6.config(background="white")
			txt_row7_7.config(background="white")
			txt_row7_8.config(background="white")
			txt_row7_9.config(background="white")
			txt_row7_10.config(background="white")
			txt_row11_t7.config(background="white")
			
			txt_row8_1.config(background="white")
			txt_row8_2.config(background="white")
			txt_row8_3.config(background="white")
			txt_row8_4.config(background="white")
			txt_row8_5.config(background="white")
			txt_row8_6.config(background="white")
			txt_row8_7.config(background="white")
			txt_row8_8.config(background="white")
			txt_row8_9.config(background="white")
			txt_row8_10.config(background="white")
			txt_row11_t8.config(background="white")
			
			txt_row9_1.config(background="white")
			txt_row9_2.config(background="white")
			txt_row9_3.config(background="white")
			txt_row9_4.config(background="white")
			txt_row9_5.config(background="white")
			txt_row9_6.config(background="white")
			txt_row9_7.config(background="white")
			txt_row9_8.config(background="white")
			txt_row9_9.config(background="white")
			txt_row9_10.config(background="white")
			txt_row11_t9.config(background="white")
			
			txt_row10_1.config(background="white")
			txt_row10_2.config(background="white")
			txt_row10_3.config(background="white")
			txt_row10_4.config(background="white")
			txt_row10_5.config(background="white")
			txt_row10_6.config(background="white")
			txt_row10_7.config(background="white")
			txt_row10_8.config(background="white")
			txt_row10_9.config(background="white")
			txt_row10_10.config(background="white")
			txt_row11_t10.config(background="white")		


			txt_row1_1.insert(tk.END, random.randint(1,5))
			txt_row1_2.insert(tk.END, random.randint(1,5))
			txt_row1_3.insert(tk.END, random.randint(1,5))
			txt_row1_4.insert(tk.END, random.randint(1,5))
			txt_row1_5.insert(tk.END, random.randint(1,5))
			txt_row1_6.insert(tk.END, random.randint(1,5))
			txt_row1_7.insert(tk.END, random.randint(1,5))
			txt_row1_8.insert(tk.END, random.randint(1,5))
			txt_row1_9.insert(tk.END, random.randint(1,5))
			txt_row1_10.insert(tk.END, random.randint(1,5))

			txt_row2_1.insert(tk.END, random.randint(1,5))
			txt_row2_2.insert(tk.END, random.randint(1,5))
			txt_row2_3.insert(tk.END, random.randint(1,5))
			txt_row2_4.insert(tk.END, random.randint(1,5))
			txt_row2_5.insert(tk.END, random.randint(1,5))
			txt_row2_6.insert(tk.END, random.randint(1,5))
			txt_row2_7.insert(tk.END, random.randint(1,5))
			txt_row2_8.insert(tk.END, random.randint(1,5))
			txt_row2_9.insert(tk.END, random.randint(1,5))
			txt_row2_10.insert(tk.END, random.randint(1,5))

			txt_row3_1.insert(tk.END, random.randint(1,5))
			txt_row3_2.insert(tk.END, random.randint(1,5))
			txt_row3_3.insert(tk.END, random.randint(1,5))
			txt_row3_4.insert(tk.END, random.randint(1,5))
			txt_row3_5.insert(tk.END, random.randint(1,5))
			txt_row3_6.insert(tk.END, random.randint(1,5))
			txt_row3_7.insert(tk.END, random.randint(1,5))
			txt_row3_8.insert(tk.END, random.randint(1,5))
			txt_row3_9.insert(tk.END, random.randint(1,5))
			txt_row3_10.insert(tk.END, random.randint(1,5))

			txt_row4_1.insert(tk.END, random.randint(1,5))
			txt_row4_2.insert(tk.END, random.randint(1,5))
			txt_row4_3.insert(tk.END, random.randint(1,5))
			txt_row4_4.insert(tk.END, random.randint(1,5))
			txt_row4_5.insert(tk.END, random.randint(1,5))
			txt_row4_6.insert(tk.END, random.randint(1,5))
			txt_row4_7.insert(tk.END, random.randint(1,5))
			txt_row4_8.insert(tk.END, random.randint(1,5))
			txt_row4_9.insert(tk.END, random.randint(1,5))
			txt_row4_10.insert(tk.END, random.randint(1,5))

			txt_row5_1.insert(tk.END, random.randint(1,5))
			txt_row5_2.insert(tk.END, random.randint(1,5))
			txt_row5_3.insert(tk.END, random.randint(1,5))
			txt_row5_4.insert(tk.END, random.randint(1,5))
			txt_row5_5.insert(tk.END, random.randint(1,5))
			txt_row5_6.insert(tk.END, random.randint(1,5))
			txt_row5_7.insert(tk.END, random.randint(1,5))
			txt_row5_8.insert(tk.END, random.randint(1,5))
			txt_row5_9.insert(tk.END, random.randint(1,5))
			txt_row5_10.insert(tk.END, random.randint(1,5))

			txt_row6_1.insert(tk.END, random.randint(1,5))
			txt_row6_2.insert(tk.END, random.randint(1,5))
			txt_row6_3.insert(tk.END, random.randint(1,5))
			txt_row6_4.insert(tk.END, random.randint(1,5))
			txt_row6_5.insert(tk.END, random.randint(1,5))
			txt_row6_6.insert(tk.END, random.randint(1,5))
			txt_row6_7.insert(tk.END, random.randint(1,5))
			txt_row6_8.insert(tk.END, random.randint(1,5))
			txt_row6_9.insert(tk.END, random.randint(1,5))
			txt_row6_10.insert(tk.END, random.randint(1,5))

			txt_row7_1.insert(tk.END, random.randint(1,5))
			txt_row7_2.insert(tk.END, random.randint(1,5))
			txt_row7_3.insert(tk.END, random.randint(1,5))
			txt_row7_4.insert(tk.END, random.randint(1,5))
			txt_row7_5.insert(tk.END, random.randint(1,5))
			txt_row7_6.insert(tk.END, random.randint(1,5))
			txt_row7_7.insert(tk.END, random.randint(1,5))
			txt_row7_8.insert(tk.END, random.randint(1,5))
			txt_row7_9.insert(tk.END, random.randint(1,5))
			txt_row7_10.insert(tk.END, random.randint(1,5))

			txt_row8_1.insert(tk.END, random.randint(1,5))
			txt_row8_2.insert(tk.END, random.randint(1,5))
			txt_row8_3.insert(tk.END, random.randint(1,5))
			txt_row8_4.insert(tk.END, random.randint(1,5))
			txt_row8_5.insert(tk.END, random.randint(1,5))
			txt_row8_6.insert(tk.END, random.randint(1,5))
			txt_row8_7.insert(tk.END, random.randint(1,5))
			txt_row8_8.insert(tk.END, random.randint(1,5))
			txt_row8_9.insert(tk.END, random.randint(1,5))
			txt_row8_10.insert(tk.END, random.randint(1,5))

			txt_row9_1.insert(tk.END, random.randint(1,5))
			txt_row9_2.insert(tk.END, random.randint(1,5))
			txt_row9_3.insert(tk.END, random.randint(1,5))
			txt_row9_4.insert(tk.END, random.randint(1,5))
			txt_row9_5.insert(tk.END, random.randint(1,5))
			txt_row9_6.insert(tk.END, random.randint(1,5))
			txt_row9_7.insert(tk.END, random.randint(1,5))
			txt_row9_8.insert(tk.END, random.randint(1,5))
			txt_row9_9.insert(tk.END, random.randint(1,5))
			txt_row9_10.insert(tk.END, random.randint(1,5))

			txt_row10_1.insert(tk.END, random.randint(1,5))
			txt_row10_2.insert(tk.END, random.randint(1,5))
			txt_row10_3.insert(tk.END, random.randint(1,5))
			txt_row10_4.insert(tk.END, random.randint(1,5))
			txt_row10_5.insert(tk.END, random.randint(1,5))
			txt_row10_6.insert(tk.END, random.randint(1,5))
			txt_row10_7.insert(tk.END, random.randint(1,5))
			txt_row10_8.insert(tk.END, random.randint(1,5))
			txt_row10_9.insert(tk.END, random.randint(1,5))
			txt_row10_10.insert(tk.END, random.randint(1,5))			
   		


def clear():

	txt_row1_1.delete("0", tk.END)
	txt_row1_2.delete("0", tk.END)
	txt_row1_3.delete("0", tk.END)
	txt_row1_4.delete("0", tk.END)
	txt_row1_5.delete("0", tk.END)
	txt_row1_6.delete("0", tk.END)
	txt_row1_7.delete("0", tk.END)
	txt_row1_8.delete("0", tk.END)
	txt_row1_9.delete("0", tk.END)
	txt_row1_10.delete("0", tk.END)

	txt_row2_1.delete("0", tk.END)
	txt_row2_2.delete("0", tk.END)
	txt_row2_3.delete("0", tk.END)
	txt_row2_4.delete("0", tk.END)
	txt_row2_5.delete("0", tk.END)
	txt_row2_6.delete("0", tk.END)
	txt_row2_7.delete("0", tk.END)
	txt_row2_8.delete("0", tk.END)
	txt_row2_9.delete("0", tk.END)
	txt_row2_10.delete("0", tk.END)

	txt_row3_1.delete("0", tk.END)
	txt_row3_2.delete("0", tk.END)
	txt_row3_3.delete("0", tk.END)
	txt_row3_4.delete("0", tk.END)
	txt_row3_5.delete("0", tk.END)
	txt_row3_6.delete("0", tk.END)
	txt_row3_7.delete("0", tk.END)
	txt_row3_8.delete("0", tk.END)
	txt_row3_9.delete("0", tk.END)
	txt_row3_10.delete("0", tk.END)

	txt_row4_1.delete("0", tk.END)
	txt_row4_2.delete("0", tk.END)
	txt_row4_3.delete("0", tk.END)
	txt_row4_4.delete("0", tk.END)
	txt_row4_5.delete("0", tk.END)
	txt_row4_6.delete("0", tk.END)
	txt_row4_7.delete("0", tk.END)
	txt_row4_8.delete("0", tk.END)
	txt_row4_9.delete("0", tk.END)
	txt_row4_10.delete("0", tk.END)

	txt_row5_1.delete("0", tk.END)
	txt_row5_2.delete("0", tk.END)
	txt_row5_3.delete("0", tk.END)
	txt_row5_4.delete("0", tk.END)
	txt_row5_5.delete("0", tk.END)
	txt_row5_6.delete("0", tk.END)
	txt_row5_7.delete("0", tk.END)
	txt_row5_8.delete("0", tk.END)
	txt_row5_9.delete("0", tk.END)
	txt_row5_10.delete("0", tk.END)

	txt_row6_1.delete("0", tk.END)
	txt_row6_2.delete("0", tk.END)
	txt_row6_3.delete("0", tk.END)
	txt_row6_4.delete("0", tk.END)
	txt_row6_5.delete("0", tk.END)
	txt_row6_6.delete("0", tk.END)
	txt_row6_7.delete("0", tk.END)
	txt_row6_8.delete("0", tk.END)
	txt_row6_9.delete("0", tk.END)
	txt_row6_10.delete("0", tk.END)

	txt_row7_1.delete("0", tk.END)
	txt_row7_2.delete("0", tk.END)
	txt_row7_3.delete("0", tk.END)
	txt_row7_4.delete("0", tk.END)
	txt_row7_5.delete("0", tk.END)
	txt_row7_6.delete("0", tk.END)
	txt_row7_7.delete("0", tk.END)
	txt_row7_8.delete("0", tk.END)
	txt_row7_9.delete("0", tk.END)
	txt_row7_10.delete("0", tk.END)

	txt_row8_1.delete("0", tk.END)
	txt_row8_2.delete("0", tk.END)
	txt_row8_3.delete("0", tk.END)
	txt_row8_4.delete("0", tk.END)
	txt_row8_5.delete("0", tk.END)
	txt_row8_6.delete("0", tk.END)
	txt_row8_7.delete("0", tk.END)
	txt_row8_8.delete("0", tk.END)
	txt_row8_9.delete("0", tk.END)
	txt_row8_10.delete("0", tk.END)

	txt_row9_1.delete("0", tk.END)
	txt_row9_2.delete("0", tk.END)
	txt_row9_3.delete("0", tk.END)
	txt_row9_4.delete("0", tk.END)
	txt_row9_5.delete("0", tk.END)
	txt_row9_6.delete("0", tk.END)
	txt_row9_7.delete("0", tk.END)
	txt_row9_8.delete("0", tk.END)
	txt_row9_9.delete("0", tk.END)
	txt_row9_10.delete("0", tk.END)

	txt_row10_1.delete("0", tk.END)
	txt_row10_2.delete("0", tk.END)
	txt_row10_3.delete("0", tk.END)
	txt_row10_4.delete("0", tk.END)
	txt_row10_5.delete("0", tk.END)
	txt_row10_6.delete("0", tk.END)
	txt_row10_7.delete("0", tk.END)
	txt_row10_8.delete("0", tk.END)
	txt_row10_9.delete("0", tk.END)
	txt_row10_10.delete("0", tk.END)

	txt_row11_t1.delete("0", tk.END)
	txt_row11_t2.delete("0", tk.END)
	txt_row11_t3.delete("0", tk.END)
	txt_row11_t4.delete("0", tk.END)
	txt_row11_t5.delete("0", tk.END)
	txt_row11_t6.delete("0", tk.END)
	txt_row11_t7.delete("0", tk.END)
	txt_row11_t8.delete("0", tk.END)
	txt_row11_t9.delete("0", tk.END)
	txt_row11_t10.delete("0", tk.END)

	txt_row1_1.insert(tk.END, 0)
	txt_row1_2.insert(tk.END, 0)
	txt_row1_3.insert(tk.END, 0)
	txt_row1_4.insert(tk.END, 0)
	txt_row1_5.insert(tk.END, 0)
	txt_row1_6.insert(tk.END, 0)
	txt_row1_7.insert(tk.END, 0)
	txt_row1_8.insert(tk.END, 0)
	txt_row1_9.insert(tk.END, 0)
	txt_row1_10.insert(tk.END, 0)

	txt_row2_1.insert(tk.END, 0)
	txt_row2_2.insert(tk.END, 0)
	txt_row2_3.insert(tk.END, 0)
	txt_row2_4.insert(tk.END, 0)
	txt_row2_5.insert(tk.END, 0)
	txt_row2_6.insert(tk.END, 0)
	txt_row2_7.insert(tk.END, 0)
	txt_row2_8.insert(tk.END, 0)
	txt_row2_9.insert(tk.END, 0)
	txt_row2_10.insert(tk.END, 0)

	txt_row3_1.insert(tk.END, 0)
	txt_row3_2.insert(tk.END, 0)
	txt_row3_3.insert(tk.END, 0)
	txt_row3_4.insert(tk.END, 0)
	txt_row3_5.insert(tk.END, 0)
	txt_row3_6.insert(tk.END, 0)
	txt_row3_7.insert(tk.END, 0)
	txt_row3_8.insert(tk.END, 0)
	txt_row3_9.insert(tk.END, 0)
	txt_row3_10.insert(tk.END, 0)

	txt_row4_1.insert(tk.END, 0)
	txt_row4_2.insert(tk.END, 0)
	txt_row4_3.insert(tk.END, 0)
	txt_row4_4.insert(tk.END, 0)
	txt_row4_5.insert(tk.END, 0)
	txt_row4_6.insert(tk.END, 0)
	txt_row4_7.insert(tk.END, 0)
	txt_row4_8.insert(tk.END, 0)
	txt_row4_9.insert(tk.END, 0)
	txt_row4_10.insert(tk.END, 0)

	txt_row5_1.insert(tk.END, 0)
	txt_row5_2.insert(tk.END, 0)
	txt_row5_3.insert(tk.END, 0)
	txt_row5_4.insert(tk.END, 0)
	txt_row5_5.insert(tk.END, 0)
	txt_row5_6.insert(tk.END, 0)
	txt_row5_7.insert(tk.END, 0)
	txt_row5_8.insert(tk.END, 0)
	txt_row5_9.insert(tk.END, 0)
	txt_row5_10.insert(tk.END, 0)

	txt_row6_1.insert(tk.END, 0)
	txt_row6_2.insert(tk.END, 0)
	txt_row6_3.insert(tk.END, 0)
	txt_row6_4.insert(tk.END, 0)
	txt_row6_5.insert(tk.END, 0)
	txt_row6_6.insert(tk.END, 0)
	txt_row6_7.insert(tk.END, 0)
	txt_row6_8.insert(tk.END, 0)
	txt_row6_9.insert(tk.END, 0)
	txt_row6_10.insert(tk.END, 0)

	txt_row7_1.insert(tk.END, 0)
	txt_row7_2.insert(tk.END, 0)
	txt_row7_3.insert(tk.END, 0)
	txt_row7_4.insert(tk.END, 0)
	txt_row7_5.insert(tk.END, 0)
	txt_row7_6.insert(tk.END, 0)
	txt_row7_7.insert(tk.END, 0)
	txt_row7_8.insert(tk.END, 0)
	txt_row7_9.insert(tk.END, 0)
	txt_row7_10.insert(tk.END, 0)

	txt_row8_1.insert(tk.END, 0)
	txt_row8_2.insert(tk.END, 0)
	txt_row8_3.insert(tk.END, 0)
	txt_row8_4.insert(tk.END, 0)
	txt_row8_5.insert(tk.END, 0)
	txt_row8_6.insert(tk.END, 0)
	txt_row8_7.insert(tk.END, 0)
	txt_row8_8.insert(tk.END, 0)
	txt_row8_9.insert(tk.END, 0)
	txt_row8_10.insert(tk.END, 0)

	txt_row9_1.insert(tk.END, 0)
	txt_row9_2.insert(tk.END, 0)
	txt_row9_3.insert(tk.END, 0)
	txt_row9_4.insert(tk.END, 0)
	txt_row9_5.insert(tk.END, 0)
	txt_row9_6.insert(tk.END, 0)
	txt_row9_7.insert(tk.END, 0)
	txt_row9_8.insert(tk.END, 0)
	txt_row9_9.insert(tk.END, 0)
	txt_row9_10.insert(tk.END, 0)

	txt_row10_1.insert(tk.END, 0)
	txt_row10_2.insert(tk.END, 0)
	txt_row10_3.insert(tk.END, 0)
	txt_row10_4.insert(tk.END, 0)
	txt_row10_5.insert(tk.END, 0)
	txt_row10_6.insert(tk.END, 0)
	txt_row10_7.insert(tk.END, 0)
	txt_row10_8.insert(tk.END, 0)
	txt_row10_9.insert(tk.END, 0)
	txt_row10_10.insert(tk.END, 0)

	cb_w0.current(0)
	cb_w1.current(0)
	cb_w2.current(0) 
	cb_w3.current(0) 
	cb_w4.current(0) 
	cb_w5.current(0) 
	cb_w6.current(0) 
	cb_w7.current(0) 
	cb_w8.current(0) 
	cb_w9.current(0) 
	cb_w10.current(0)	


	txt_row1_1.config(background="white")
	txt_row1_2.config(background="white")
	txt_row1_3.config(background="white")
	txt_row1_4.config(background="white")
	txt_row1_5.config(background="white")
	txt_row1_6.config(background="white")
	txt_row1_7.config(background="white")
	txt_row1_8.config(background="white")
	txt_row1_9.config(background="white")
	txt_row1_10.config(background="white")
	txt_row11_t1.config(background="white")

	txt_row2_1.config(background="white")
	txt_row2_2.config(background="white")
	txt_row2_3.config(background="white")
	txt_row2_4.config(background="white")
	txt_row2_5.config(background="white")
	txt_row2_6.config(background="white")
	txt_row2_7.config(background="white")
	txt_row2_8.config(background="white")
	txt_row2_9.config(background="white")
	txt_row2_10.config(background="white")
	txt_row11_t2.config(background="white")

	txt_row3_1.config(background="white")
	txt_row3_2.config(background="white")
	txt_row3_3.config(background="white")
	txt_row3_4.config(background="white")
	txt_row3_5.config(background="white")
	txt_row3_6.config(background="white")
	txt_row3_7.config(background="white")
	txt_row3_8.config(background="white")
	txt_row3_9.config(background="white")
	txt_row3_10.config(background="white")
	txt_row11_t3.config(background="white")
	
	txt_row4_1.config(background="white")
	txt_row4_2.config(background="white")
	txt_row4_3.config(background="white")
	txt_row4_4.config(background="white")
	txt_row4_5.config(background="white")
	txt_row4_6.config(background="white")
	txt_row4_7.config(background="white")
	txt_row4_8.config(background="white")
	txt_row4_9.config(background="white")
	txt_row4_10.config(background="white")
	txt_row11_t4.config(background="white")

	txt_row5_1.config(background="white")
	txt_row5_2.config(background="white")
	txt_row5_3.config(background="white")
	txt_row5_4.config(background="white")
	txt_row5_5.config(background="white")
	txt_row5_6.config(background="white")
	txt_row5_7.config(background="white")
	txt_row5_8.config(background="white")
	txt_row5_9.config(background="white")
	txt_row5_10.config(background="white")
	txt_row11_t5.config(background="white")
	
	txt_row6_1.config(background="white")
	txt_row6_2.config(background="white")
	txt_row6_3.config(background="white")
	txt_row6_4.config(background="white")
	txt_row6_5.config(background="white")
	txt_row6_6.config(background="white")
	txt_row6_7.config(background="white")
	txt_row6_8.config(background="white")
	txt_row6_9.config(background="white")
	txt_row6_10.config(background="white")
	txt_row11_t6.config(background="white")
	
	txt_row7_1.config(background="white")
	txt_row7_2.config(background="white")
	txt_row7_3.config(background="white")
	txt_row7_4.config(background="white")
	txt_row7_5.config(background="white")
	txt_row7_6.config(background="white")
	txt_row7_7.config(background="white")
	txt_row7_8.config(background="white")
	txt_row7_9.config(background="white")
	txt_row7_10.config(background="white")
	txt_row11_t7.config(background="white")
	
	txt_row8_1.config(background="white")
	txt_row8_2.config(background="white")
	txt_row8_3.config(background="white")
	txt_row8_4.config(background="white")
	txt_row8_5.config(background="white")
	txt_row8_6.config(background="white")
	txt_row8_7.config(background="white")
	txt_row8_8.config(background="white")
	txt_row8_9.config(background="white")
	txt_row8_10.config(background="white")
	txt_row11_t8.config(background="white")
	
	txt_row9_1.config(background="white")
	txt_row9_2.config(background="white")
	txt_row9_3.config(background="white")
	txt_row9_4.config(background="white")
	txt_row9_5.config(background="white")
	txt_row9_6.config(background="white")
	txt_row9_7.config(background="white")
	txt_row9_8.config(background="white")
	txt_row9_9.config(background="white")
	txt_row9_10.config(background="white")
	txt_row11_t9.config(background="white")
	
	txt_row10_1.config(background="white")
	txt_row10_2.config(background="white")
	txt_row10_3.config(background="white")
	txt_row10_4.config(background="white")
	txt_row10_5.config(background="white")
	txt_row10_6.config(background="white")
	txt_row10_7.config(background="white")
	txt_row10_8.config(background="white")
	txt_row10_9.config(background="white")
	txt_row10_10.config(background="white")
	txt_row11_t10.config(background="white")

def calc():

	rows = []	

	row1 = (int(n1.get()) * int(txt_row1_1.get())) + (int(n2.get()) * int(txt_row1_2.get())) + (int(n3.get()) * int(txt_row1_3.get())) + (int(n4.get()) * int(txt_row1_4.get())) + (int(n5.get()) * int(txt_row1_5.get())) + (int(n6.get()) * int(txt_row1_6.get())) + (int(n7.get()) * int(txt_row1_7.get())) + (int(n8.get()) * int(txt_row1_8.get())) + (int(n9.get()) * int(txt_row1_9.get())) + (int(n10.get()) * int(txt_row1_10.get()))
	row2 = (int(n1.get()) * int(txt_row2_1.get())) + (int(n2.get()) * int(txt_row2_2.get())) + (int(n3.get()) * int(txt_row2_3.get())) + (int(n4.get()) * int(txt_row2_4.get())) + (int(n5.get()) * int(txt_row2_5.get())) + (int(n6.get()) * int(txt_row2_6.get())) + (int(n7.get()) * int(txt_row2_7.get())) + (int(n8.get()) * int(txt_row2_8.get())) + (int(n9.get()) * int(txt_row2_9.get())) + (int(n10.get()) * int(txt_row2_10.get()))
	row3 = (int(n1.get()) * int(txt_row3_1.get())) + (int(n2.get()) * int(txt_row3_2.get())) + (int(n3.get()) * int(txt_row3_3.get())) + (int(n4.get()) * int(txt_row3_4.get())) + (int(n5.get()) * int(txt_row3_5.get())) + (int(n6.get()) * int(txt_row3_6.get())) + (int(n7.get()) * int(txt_row3_7.get())) + (int(n8.get()) * int(txt_row3_8.get())) + (int(n9.get()) * int(txt_row3_9.get())) + (int(n10.get()) * int(txt_row3_10.get()))
	row4 = (int(n1.get()) * int(txt_row4_1.get())) + (int(n2.get()) * int(txt_row4_2.get())) + (int(n3.get()) * int(txt_row4_3.get())) + (int(n4.get()) * int(txt_row4_4.get())) + (int(n5.get()) * int(txt_row4_5.get())) + (int(n6.get()) * int(txt_row4_6.get())) + (int(n7.get()) * int(txt_row4_7.get())) + (int(n8.get()) * int(txt_row4_8.get())) + (int(n9.get()) * int(txt_row4_9.get())) + (int(n10.get()) * int(txt_row4_10.get()))
	row5 = (int(n1.get()) * int(txt_row5_1.get())) + (int(n2.get()) * int(txt_row5_2.get())) + (int(n3.get()) * int(txt_row5_3.get())) + (int(n4.get()) * int(txt_row5_4.get())) + (int(n5.get()) * int(txt_row5_5.get())) + (int(n6.get()) * int(txt_row5_6.get())) + (int(n7.get()) * int(txt_row5_7.get())) + (int(n8.get()) * int(txt_row5_8.get())) + (int(n9.get()) * int(txt_row5_9.get())) + (int(n10.get()) * int(txt_row5_10.get()))
	row6 = (int(n1.get()) * int(txt_row6_1.get())) + (int(n2.get()) * int(txt_row6_2.get())) + (int(n3.get()) * int(txt_row6_3.get())) + (int(n4.get()) * int(txt_row6_4.get())) + (int(n5.get()) * int(txt_row6_5.get())) + (int(n6.get()) * int(txt_row6_6.get())) + (int(n7.get()) * int(txt_row6_7.get())) + (int(n8.get()) * int(txt_row6_8.get())) + (int(n9.get()) * int(txt_row6_9.get())) + (int(n10.get()) * int(txt_row6_10.get()))
	row7 = (int(n1.get()) * int(txt_row7_1.get())) + (int(n2.get()) * int(txt_row7_2.get())) + (int(n3.get()) * int(txt_row7_3.get())) + (int(n4.get()) * int(txt_row7_4.get())) + (int(n5.get()) * int(txt_row7_5.get())) + (int(n6.get()) * int(txt_row7_6.get())) + (int(n7.get()) * int(txt_row7_7.get())) + (int(n8.get()) * int(txt_row7_8.get())) + (int(n9.get()) * int(txt_row7_9.get())) + (int(n10.get()) * int(txt_row7_10.get()))
	row8 = (int(n1.get()) * int(txt_row8_1.get())) + (int(n2.get()) * int(txt_row8_2.get())) + (int(n3.get()) * int(txt_row8_3.get())) + (int(n4.get()) * int(txt_row8_4.get())) + (int(n5.get()) * int(txt_row8_5.get())) + (int(n6.get()) * int(txt_row8_6.get())) + (int(n7.get()) * int(txt_row8_7.get())) + (int(n8.get()) * int(txt_row8_8.get())) + (int(n9.get()) * int(txt_row8_9.get())) + (int(n10.get()) * int(txt_row8_10.get()))
	row9 = (int(n1.get()) * int(txt_row9_1.get())) + (int(n2.get()) * int(txt_row9_2.get())) + (int(n3.get()) * int(txt_row9_3.get())) + (int(n4.get()) * int(txt_row9_4.get())) + (int(n5.get()) * int(txt_row9_5.get())) + (int(n6.get()) * int(txt_row9_6.get())) + (int(n7.get()) * int(txt_row9_7.get())) + (int(n8.get()) * int(txt_row9_8.get())) + (int(n9.get()) * int(txt_row9_9.get())) + (int(n10.get()) * int(txt_row9_10.get()))
	row10 = (int(n1.get()) * int(txt_row10_1.get())) + (int(n2.get()) * int(txt_row10_2.get())) + (int(n3.get()) * int(txt_row10_3.get())) + (int(n4.get()) * int(txt_row10_4.get())) + (int(n5.get()) * int(txt_row10_5.get())) + (int(n6.get()) * int(txt_row10_6.get())) + (int(n7.get()) * int(txt_row10_7.get())) + (int(n8.get()) * int(txt_row10_8.get())) + (int(n9.get()) * int(txt_row10_9.get())) + (int(n10.get()) * int(txt_row10_10.get()))

	rows.append(row1)
	rows.append(row2)
	rows.append(row3)
	rows.append(row4)
	rows.append(row5)
	rows.append(row6)
	rows.append(row7)
	rows.append(row8)
	rows.append(row9)
	rows.append(row10)

	txt_row11_t1.insert(tk.END, row1)
	txt_row11_t2.insert(tk.END, row2)
	txt_row11_t3.insert(tk.END, row3)
	txt_row11_t4.insert(tk.END, row4)
	txt_row11_t5.insert(tk.END, row5)
	txt_row11_t6.insert(tk.END, row6)
	txt_row11_t7.insert(tk.END, row7)
	txt_row11_t8.insert(tk.END, row8)
	txt_row11_t9.insert(tk.END, row9)
	txt_row11_t10.insert(tk.END, row10)

	winner = max(rows)
	#index of winner in rows
	index = rows.index(winner)
	print(index)
	print(rows)

	if sum(rows) > 0:
		if index == 0:
			txt_row1_1.config(background="yellow")
			txt_row1_2.config(background="yellow")
			txt_row1_3.config(background="yellow")
			txt_row1_4.config(background="yellow")
			txt_row1_5.config(background="yellow")
			txt_row1_6.config(background="yellow")
			txt_row1_7.config(background="yellow")
			txt_row1_8.config(background="yellow")
			txt_row1_9.config(background="yellow")
			txt_row1_10.config(background="yellow")
			txt_row11_t1.config(background="yellow")
		elif index == 1:	
			txt_row2_1.config(background="yellow")
			txt_row2_2.config(background="yellow")
			txt_row2_3.config(background="yellow")
			txt_row2_4.config(background="yellow")
			txt_row2_5.config(background="yellow")
			txt_row2_6.config(background="yellow")
			txt_row2_7.config(background="yellow")
			txt_row2_8.config(background="yellow")
			txt_row2_9.config(background="yellow")
			txt_row2_10.config(background="yellow")
			txt_row11_t2.config(background="yellow")
		elif index == 2:	
			txt_row3_1.config(background="yellow")
			txt_row3_2.config(background="yellow")
			txt_row3_3.config(background="yellow")
			txt_row3_4.config(background="yellow")
			txt_row3_5.config(background="yellow")
			txt_row3_6.config(background="yellow")
			txt_row3_7.config(background="yellow")
			txt_row3_8.config(background="yellow")
			txt_row3_9.config(background="yellow")
			txt_row3_10.config(background="yellow")
			txt_row11_t3.config(background="yellow")
		elif index == 3:	
			txt_row4_1.config(background="yellow")
			txt_row4_2.config(background="yellow")
			txt_row4_3.config(background="yellow")
			txt_row4_4.config(background="yellow")
			txt_row4_5.config(background="yellow")
			txt_row4_6.config(background="yellow")
			txt_row4_7.config(background="yellow")
			txt_row4_8.config(background="yellow")
			txt_row4_9.config(background="yellow")
			txt_row4_10.config(background="yellow")
			txt_row11_t4.config(background="yellow")
		elif index == 4:	
			txt_row5_1.config(background="yellow")
			txt_row5_2.config(background="yellow")
			txt_row5_3.config(background="yellow")
			txt_row5_4.config(background="yellow")
			txt_row5_5.config(background="yellow")
			txt_row5_6.config(background="yellow")
			txt_row5_7.config(background="yellow")
			txt_row5_8.config(background="yellow")
			txt_row5_9.config(background="yellow")
			txt_row5_10.config(background="yellow")
			txt_row11_t5.config(background="yellow")
		elif index == 5:	
			txt_row6_1.config(background="yellow")
			txt_row6_2.config(background="yellow")
			txt_row6_3.config(background="yellow")
			txt_row6_4.config(background="yellow")
			txt_row6_5.config(background="yellow")
			txt_row6_6.config(background="yellow")
			txt_row6_7.config(background="yellow")
			txt_row6_8.config(background="yellow")
			txt_row6_9.config(background="yellow")
			txt_row6_10.config(background="yellow")
			txt_row11_t6.config(background="yellow")
		elif index == 6:	
			txt_row7_1.config(background="yellow")
			txt_row7_2.config(background="yellow")
			txt_row7_3.config(background="yellow")
			txt_row7_4.config(background="yellow")
			txt_row7_5.config(background="yellow")
			txt_row7_6.config(background="yellow")
			txt_row7_7.config(background="yellow")
			txt_row7_8.config(background="yellow")
			txt_row7_9.config(background="yellow")
			txt_row7_10.config(background="yellow")
			txt_row11_t7.config(background="yellow")
		elif index == 7:	
			txt_row8_1.config(background="yellow")
			txt_row8_2.config(background="yellow")
			txt_row8_3.config(background="yellow")
			txt_row8_4.config(background="yellow")
			txt_row8_5.config(background="yellow")
			txt_row8_6.config(background="yellow")
			txt_row8_7.config(background="yellow")
			txt_row8_8.config(background="yellow")
			txt_row8_9.config(background="yellow")
			txt_row8_10.config(background="yellow")
			txt_row11_t8.config(background="yellow")
		elif index == 8:	
			txt_row9_1.config(background="yellow")
			txt_row9_2.config(background="yellow")
			txt_row9_3.config(background="yellow")
			txt_row9_4.config(background="yellow")
			txt_row9_5.config(background="yellow")
			txt_row9_6.config(background="yellow")
			txt_row9_7.config(background="yellow")
			txt_row9_8.config(background="yellow")
			txt_row9_9.config(background="yellow")
			txt_row9_10.config(background="yellow")
			txt_row11_t9.config(background="yellow")
		elif index == 9:	
			txt_row10_1.config(background="yellow")
			txt_row10_2.config(background="yellow")
			txt_row10_3.config(background="yellow")
			txt_row10_4.config(background="yellow")
			txt_row10_5.config(background="yellow")
			txt_row10_6.config(background="yellow")
			txt_row10_7.config(background="yellow")
			txt_row10_8.config(background="yellow")
			txt_row10_9.config(background="yellow")
			txt_row10_10.config(background="yellow")
			txt_row11_t10.config(background="yellow")

def rename(var):
	if var < 11:
		answer = simpledialog.askstring("Input", f"Enter a name for: Factor {var}", parent=window)
		if var == 1:
			btn_factor1.config(text=answer)
		elif var == 2:
			btn_factor2.config(text=answer)
		elif var == 3:
			btn_factor3.config(text=answer)
		elif var == 4:
			btn_factor4.config(text=answer)
		elif var == 5:
			btn_factor5.config(text=answer)
		elif var == 6:
			btn_factor6.config(text=answer)
		elif var == 7:
			btn_factor7.config(text=answer)
		elif var == 8:
			btn_factor8.config(text=answer)
		elif var == 9:
			btn_factor9.config(text=answer)
		elif var == 10:
			btn_factor10.config(text=answer)																								
	else:
		answer = simpledialog.askstring("Input", f"Enter a name for: Decision {var - 10}", parent=window)
		if var == 11:
			btn_decision1.config(text=answer)
		elif var == 12:
			btn_decision2.config(text=answer)
		elif var == 13:
			btn_decision3.config(text=answer)
		elif var == 14:
			btn_decision4.config(text=answer)
		elif var == 15:
			btn_decision5.config(text=answer)
		elif var == 16:
			btn_decision6.config(text=answer)
		elif var == 17:
			btn_decision7.config(text=answer)
		elif var == 18:
			btn_decision8.config(text=answer)
		elif var == 19:
			btn_decision9.config(text=answer)
		elif var == 20:
			btn_decision10.config(text=answer)

# SETUP ELEMENTS --------------------

lb_title = tk.Label(text="PYTHON Decision Matrix", background=BG, font="arial 28 bold")			

lb_factors_title = tk.Label(text="Decision Factors", background=BG, font="arial 12 bold")

btn_factor1 = tk.Button(text="Factor 1", width=12, background=BG_FACTOR, command=lambda x=1:rename(x))
btn_factor2 = tk.Button(text="Factor 2", width=12, background=BG_FACTOR, command=lambda x=2:rename(x))
btn_factor3 = tk.Button(text="Factor 3", width=12, background=BG_FACTOR, command=lambda x=3:rename(x))
btn_factor4 = tk.Button(text="Factor 4", width=12, background=BG_FACTOR, command=lambda x=4:rename(x))
btn_factor5 = tk.Button(text="Factor 5", width=12, background=BG_FACTOR, command=lambda x=5:rename(x))
btn_factor6 = tk.Button(text="Factor 6", width=12, background=BG_FACTOR, command=lambda x=6:rename(x))
btn_factor7 = tk.Button(text="Factor 7", width=12, background=BG_FACTOR, command=lambda x=7:rename(x))
btn_factor8 = tk.Button(text="Factor 8", width=12, background=BG_FACTOR, command=lambda x=8:rename(x))
btn_factor9 = tk.Button(text="Factor 9", width=12, background=BG_FACTOR, command=lambda x=9:rename(x))
btn_factor10 = tk.Button(text="Factor 10", width=12, background=BG_FACTOR, command=lambda x=10:rename(x))
lb_total = tk.Label(text="TOTAL", background=BG, font="arial 12 bold")

lb_decisions_title = tk.Label(text="Decisions", background=BG, font="arial 12 bold")
lb_instructions1 = tk.Label(text="Score each option from 1 (Very Poor) to 5 (Very Good).", font="arial 10", background=BG)

btn_decision1 = tk.Button(text="Decision 1", width=20, background=BG_DECISION, command=lambda x=11:rename(x))
btn_decision2 = tk.Button(text="Decision 2", width=20, background=BG_DECISION, command=lambda x=12:rename(x))
btn_decision3 = tk.Button(text="Decision 3", width=20, background=BG_DECISION, command=lambda x=13:rename(x))
btn_decision4 = tk.Button(text="Decision 4", width=20, background=BG_DECISION, command=lambda x=14:rename(x))
btn_decision5 = tk.Button(text="Decision 5", width=20, background=BG_DECISION, command=lambda x=15:rename(x))
btn_decision6 = tk.Button(text="Decision 6", width=20, background=BG_DECISION, command=lambda x=16:rename(x))
btn_decision7 = tk.Button(text="Decision 7", width=20, background=BG_DECISION, command=lambda x=17:rename(x))
btn_decision8 = tk.Button(text="Decision 8", width=20, background=BG_DECISION, command=lambda x=18:rename(x))
btn_decision9 = tk.Button(text="Decision 9", width=20, background=BG_DECISION, command=lambda x=19:rename(x))
btn_decision10 = tk.Button(text="Decision 10", width=20, background=BG_DECISION, command=lambda x=20:rename(x))


# TEXT COLUMNS

txt_row1_1 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center', name="row1_1")
txt_row1_2 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row1_3 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row1_4 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row1_5 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row1_6 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row1_7 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row1_8 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row1_9 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row1_10 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')

txt_row2_1 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row2_2 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row2_3 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row2_4 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row2_5 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row2_6 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row2_7 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row2_8 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row2_9 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row2_10 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')

txt_row3_1 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row3_2 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row3_3 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row3_4 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row3_5 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row3_6 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row3_7 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row3_8 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row3_9 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row3_10 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')

txt_row4_1 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row4_2 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row4_3 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row4_4 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row4_5 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row4_6 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row4_7 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row4_8 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row4_9 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row4_10 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')

txt_row5_1 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row5_2 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row5_3 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row5_4 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row5_5 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row5_6 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row5_7 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row5_8 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row5_9 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row5_10 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')

txt_row6_1 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row6_2 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row6_3 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row6_4 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row6_5 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row6_6 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row6_7 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row6_8 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row6_9 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row6_10 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')

txt_row7_1 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row7_2 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row7_3 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row7_4 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row7_5 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row7_6 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row7_7 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row7_8 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row7_9 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row7_10 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')

txt_row8_1 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row8_2 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row8_3 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row8_4 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row8_5 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row8_6 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row8_7 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row8_8 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row8_9 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row8_10 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')

txt_row9_1 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row9_2 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row9_3 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row9_4 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row9_5 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row9_6 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row9_7 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row9_8 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row9_9 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row9_10 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')

txt_row10_1 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row10_2 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row10_3 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row10_4 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row10_5 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row10_6 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row10_7 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row10_8 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row10_9 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row10_10 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')

txt_row11_t1 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row11_t2 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row11_t3 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row11_t4 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row11_t5 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row11_t6 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row11_t7 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row11_t8 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row11_t9 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')
txt_row11_t10 = tk.Entry(width=TXTWIDTH, font="arial 10 bold", justify='center')

lb_instructions2 = tk.Label(text="Importance of Factors: Score each weight from 1 (Unimportant) to 5 (Very Important).", font="arial 10", background=BG)

lb_weight_values = tk.Label(text="Weight Values", font="arial 12 bold", background=BG)

lb_factors_1 = tk.Label(text="Factor 1", font="arial 9 bold", background=BG)
lb_factors_2 = tk.Label(text="Factor 2", font="arial 9 bold", background=BG)
lb_factors_3 = tk.Label(text="Factor 3", font="arial 9 bold", background=BG)
lb_factors_4 = tk.Label(text="Factor 4", font="arial 9 bold", background=BG)
lb_factors_5 = tk.Label(text="Factor 5", font="arial 9 bold", background=BG)
lb_factors_6 = tk.Label(text="Factor 6", font="arial 9 bold", background=BG)
lb_factors_7 = tk.Label(text="Factor 7", font="arial 9 bold", background=BG)
lb_factors_8 = tk.Label(text="Factor 8", font="arial 9 bold", background=BG)
lb_factors_9 = tk.Label(text="Factor 9", font="arial 9 bold", background=BG)
lb_factors_11 = tk.Label(text="Factor 10", font="arial 9 bold", background=BG)

lb_spacer1 = tk.Label(text="|", font="arial 12 bold", background=BG)
lb_spacer2 = tk.Label(text="|", font="arial 12 bold", background=BG)
lb_spacer3 = tk.Label(text="|", font="arial 12 bold", background=BG)
lb_spacer4 = tk.Label(text="|", font="arial 12 bold", background=BG)
lb_spacer5 = tk.Label(text="|", font="arial 12 bold", background=BG)
lb_spacer6 = tk.Label(text="|", font="arial 12 bold", background=BG)
lb_spacer7 = tk.Label(text="|", font="arial 12 bold", background=BG)
lb_spacer8 = tk.Label(text="|", font="arial 12 bold", background=BG)
lb_spacer9 = tk.Label(text="|", font="arial 12 bold", background=BG)
lb_spacer10 = tk.Label(text="|", font="arial 12 bold", background=BG)


#v = tk.DoubleVar()   # Holds a float; default value 0.0
#v = tk.IntVar()      # Holds an int; default value 0
#v = tk.StringVar()   # Holds a string; default value ''

# Combobox creation 
n0_preload = tk.StringVar() 
cb_w0 = ttk.Combobox(width=20, font="arial 12 bold", textvariable=n0_preload, justify="center", state="readonly")
# Adding combobox drop down list 
cb_w0['values'] = ("TEMPLATES",
					"Comparing Jobs",
					"Moving / Relocating",
					"Buying a Car",
					"Buying a Computer",
					"TEST DATA")

# Combobox creation 
n1 = tk.StringVar() 
cb_w1 = ttk.Combobox(width=TXTWIDTH, textvariable=n1, justify="center", state="readonly") 
  
# Adding combobox drop down list 
cb_w1['values'] = (1, 2, 3, 4, 5)

n2 = tk.StringVar() 
cb_w2 = ttk.Combobox(width=TXTWIDTH, textvariable=n2, justify="center", state="readonly") 
  
# Adding combobox drop down list 
cb_w2['values'] = (1, 2, 3, 4, 5) 

n3 = tk.StringVar() 
cb_w3 = ttk.Combobox(width=TXTWIDTH, textvariable=n3, justify="center", state="readonly") 
  
# Adding combobox drop down list 
cb_w3['values'] = (1, 2, 3, 4, 5) 

n4 = tk.StringVar() 
cb_w4 = ttk.Combobox(width=TXTWIDTH, textvariable=n4, justify="center", state="readonly") 
  
# Adding combobox drop down list 
cb_w4['values'] = (1, 2, 3, 4, 5) 

n5 = tk.StringVar() 
cb_w5 = ttk.Combobox(width=TXTWIDTH, textvariable=n5, justify="center", state="readonly") 
  
# Adding combobox drop down list 
cb_w5['values'] = (1, 2, 3, 4, 5) 

n6 = tk.StringVar() 
cb_w6 = ttk.Combobox(width=TXTWIDTH, textvariable=n6, justify="center", state="readonly") 
  
# Adding combobox drop down list 
cb_w6['values'] = (1, 2, 3, 4, 5) 

n7 = tk.StringVar() 
cb_w7 = ttk.Combobox(width=TXTWIDTH, textvariable=n7, justify="center", state="readonly") 
  
# Adding combobox drop down list 
cb_w7['values'] = (1, 2, 3, 4, 5) 

n8 = tk.StringVar() 
cb_w8 = ttk.Combobox(width=TXTWIDTH, textvariable=n8, justify="center", state="readonly") 
  
# Adding combobox drop down list 
cb_w8['values'] = (1, 2, 3, 4, 5) 

n9 = tk.StringVar() 
cb_w9 = ttk.Combobox(width=TXTWIDTH, textvariable=n9, justify="center", state="readonly") 
  
# Adding combobox drop down list 
cb_w9['values'] = (1, 2, 3, 4, 5) 

n10 = tk.StringVar() 
cb_w10 = ttk.Combobox(width=TXTWIDTH, textvariable=n10, justify="center", state="readonly") 
  
# Adding combobox drop down list 
cb_w10['values'] = (1, 2, 3, 4, 5)

btn_clear = tk.Button(text="Clear Table", width=12, height=1, command=clear, font="arial 12 bold", background="tomato")
lb_weight_values = tk.Label(text="10x10 Decision Matrix", font="arial 22 bold", background=BG)
btn_calculate = tk.Button(text="CALCULATE", width=12, height=1, command=calc, font="arial 12 bold", background="green yellow")

clear()

# BUILD GUI ---------------------

cb_w0.grid(row=1, column=0, padx=10) 
cb_w0.current(0)

lb_title.grid(row=1, column=4, columnspan=4)

lb_factors_title.grid(row=2, column=0)

btn_factor1.grid(row=2, column=1, padx=15, pady=35)
btn_factor2.grid(row=2, column=2, padx=15)
btn_factor3.grid(row=2, column=3, padx=15)
btn_factor4.grid(row=2, column=4, padx=15)
btn_factor5.grid(row=2, column=5, padx=15)
btn_factor6.grid(row=2, column=6, padx=15)
btn_factor7.grid(row=2, column=7, padx=15)
btn_factor8.grid(row=2, column=8, padx=15)
btn_factor9.grid(row=2, column=9, padx=15)
btn_factor10.grid(row=2, column=10, padx=15)
lb_total.grid(row=2, column=12, padx=25)

lb_decisions_title.grid(row=3, column=0)
lb_instructions1.grid(row=3, column=3, columnspan=6)

btn_decision1.grid(row=4, column=0, pady=15)
btn_decision2.grid(row=5, column=0, pady=15)
btn_decision3.grid(row=6, column=0, pady=15)
btn_decision4.grid(row=7, column=0, pady=15)
btn_decision5.grid(row=8, column=0, pady=15)
btn_decision6.grid(row=9, column=0, pady=15)
btn_decision7.grid(row=10, column=0, pady=15)
btn_decision8.grid(row=11, column=0, pady=15)
btn_decision9.grid(row=12, column=0, pady=15)
btn_decision10.grid(row=13, column=0, pady=15)


# TEXT COLUMNS

txt_row1_1.grid(row=4, column=1)
txt_row1_2.grid(row=4, column=2)
txt_row1_3.grid(row=4, column=3)
txt_row1_4.grid(row=4, column=4)
txt_row1_5.grid(row=4, column=5)
txt_row1_6.grid(row=4, column=6)
txt_row1_7.grid(row=4, column=7)
txt_row1_8.grid(row=4, column=8)
txt_row1_9.grid(row=4, column=9)
txt_row1_10.grid(row=4, column=10)

txt_row2_1.grid(row=5, column=1)
txt_row2_2.grid(row=5, column=2)
txt_row2_3.grid(row=5, column=3)
txt_row2_4.grid(row=5, column=4)
txt_row2_5.grid(row=5, column=5)
txt_row2_6.grid(row=5, column=6)
txt_row2_7.grid(row=5, column=7)
txt_row2_8.grid(row=5, column=8)
txt_row2_9.grid(row=5, column=9)
txt_row2_10.grid(row=5, column=10)

txt_row3_1.grid(row=6, column=1)
txt_row3_2.grid(row=6, column=2)
txt_row3_3.grid(row=6, column=3)
txt_row3_4.grid(row=6, column=4)
txt_row3_5.grid(row=6, column=5)
txt_row3_6.grid(row=6, column=6)
txt_row3_7.grid(row=6, column=7)
txt_row3_8.grid(row=6, column=8)
txt_row3_9.grid(row=6, column=9)
txt_row3_10.grid(row=6, column=10)

txt_row4_1.grid(row=7, column=1)
txt_row4_2.grid(row=7, column=2)
txt_row4_3.grid(row=7, column=3)
txt_row4_4.grid(row=7, column=4)
txt_row4_5.grid(row=7, column=5)
txt_row4_6.grid(row=7, column=6)
txt_row4_7.grid(row=7, column=7)
txt_row4_8.grid(row=7, column=8)
txt_row4_9.grid(row=7, column=9)
txt_row4_10.grid(row=7, column=10)

txt_row5_1.grid(row=8, column=1)
txt_row5_2.grid(row=8, column=2)
txt_row5_3.grid(row=8, column=3)
txt_row5_4.grid(row=8, column=4)
txt_row5_5.grid(row=8, column=5)
txt_row5_6.grid(row=8, column=6)
txt_row5_7.grid(row=8, column=7)
txt_row5_8.grid(row=8, column=8)
txt_row5_9.grid(row=8, column=9)
txt_row5_10.grid(row=8, column=10)

txt_row6_1.grid(row=9, column=1)
txt_row6_2.grid(row=9, column=2)
txt_row6_3.grid(row=9, column=3)
txt_row6_4.grid(row=9, column=4)
txt_row6_5.grid(row=9, column=5)
txt_row6_6.grid(row=9, column=6)
txt_row6_7.grid(row=9, column=7)
txt_row6_8.grid(row=9, column=8)
txt_row6_9.grid(row=9, column=9)
txt_row6_10.grid(row=9, column=10)

txt_row7_1.grid(row=10, column=1)
txt_row7_2.grid(row=10, column=2)
txt_row7_3.grid(row=10, column=3)
txt_row7_4.grid(row=10, column=4)
txt_row7_5.grid(row=10, column=5)
txt_row7_6.grid(row=10, column=6)
txt_row7_7.grid(row=10, column=7)
txt_row7_8.grid(row=10, column=8)
txt_row7_9.grid(row=10, column=9)
txt_row7_10.grid(row=10, column=10)

txt_row8_1.grid(row=11, column=1)
txt_row8_2.grid(row=11, column=2)
txt_row8_3.grid(row=11, column=3)
txt_row8_4.grid(row=11, column=4)
txt_row8_5.grid(row=11, column=5)
txt_row8_6.grid(row=11, column=6)
txt_row8_7.grid(row=11, column=7)
txt_row8_8.grid(row=11, column=8)
txt_row8_9.grid(row=11, column=9)
txt_row8_10.grid(row=11, column=10)

txt_row9_1.grid(row=12, column=1)
txt_row9_2.grid(row=12, column=2)
txt_row9_3.grid(row=12, column=3)
txt_row9_4.grid(row=12, column=4)
txt_row9_5.grid(row=12, column=5)
txt_row9_6.grid(row=12, column=6)
txt_row9_7.grid(row=12, column=7)
txt_row9_8.grid(row=12, column=8)
txt_row9_9.grid(row=12, column=9)
txt_row9_10.grid(row=12, column=10)

txt_row10_1.grid(row=13, column=1)
txt_row10_2.grid(row=13, column=2)
txt_row10_3.grid(row=13, column=3)
txt_row10_4.grid(row=13, column=4)
txt_row10_5.grid(row=13, column=5)
txt_row10_6.grid(row=13, column=6)
txt_row10_7.grid(row=13, column=7)
txt_row10_8.grid(row=13, column=8)
txt_row10_9.grid(row=13, column=9)
txt_row10_10.grid(row=13, column=10)

lb_spacer1.grid(row=4, column=11)
lb_spacer2.grid(row=5, column=11)
lb_spacer3.grid(row=6, column=11)
lb_spacer4.grid(row=7, column=11)
lb_spacer5.grid(row=8, column=11)
lb_spacer6.grid(row=9, column=11)
lb_spacer7.grid(row=10, column=11)
lb_spacer8.grid(row=11, column=11)
lb_spacer9.grid(row=12, column=11)
lb_spacer10.grid(row=13, column=11)

txt_row11_t1.grid(row=4, column=12)
txt_row11_t2.grid(row=5, column=12)
txt_row11_t3.grid(row=6, column=12)
txt_row11_t4.grid(row=7, column=12)
txt_row11_t5.grid(row=8, column=12)
txt_row11_t6.grid(row=9, column=12)
txt_row11_t7.grid(row=10, column=12)
txt_row11_t8.grid(row=11, column=12)
txt_row11_t9.grid(row=12, column=12)
txt_row11_t10.grid(row=13, column=12)

lb_instructions2.grid(row=15, column=3, columnspan=6, pady=15)

lb_factors_1.grid(row=16, column=1)
lb_factors_2.grid(row=16, column=2)
lb_factors_3.grid(row=16, column=3)
lb_factors_4.grid(row=16, column=4)
lb_factors_5.grid(row=16, column=5)
lb_factors_6.grid(row=16, column=6)
lb_factors_7.grid(row=16, column=7)
lb_factors_8.grid(row=16, column=8)
lb_factors_9.grid(row=16, column=9)
lb_factors_11.grid(row=16, column=10)

lb_weight_values.grid(row=17, column=0)

cb_w1.grid(row=17, column=1, padx=10) 
cb_w1.current(0)

cb_w2.grid(row=17, column=2, padx=10) 
cb_w2.current(0) 

cb_w3.grid(row=17, column=3, padx=10) 
cb_w3.current(0) 

cb_w4.grid(row=17, column=4, padx=10) 
cb_w4.current(0) 

cb_w5.grid(row=17, column=5, padx=10) 
cb_w5.current(0) 

cb_w6.grid(row=17, column=6, padx=10) 
cb_w6.current(0) 

cb_w7.grid(row=17, column=7, padx=10) 
cb_w7.current(0) 

cb_w8.grid(row=17, column=8, padx=10) 
cb_w8.current(0) 

cb_w9.grid(row=17, column=9, padx=10) 
cb_w9.current(0) 

cb_w10.grid(row=17, column=10, padx=10) 
cb_w10.current(0)

btn_clear.grid(row=18, column=1) 
lb_weight_values.grid(row=18, column=3, columnspan=6, pady=30) 
btn_calculate.grid(row=18, column=10)

cb_w0.bind("<<ComboboxSelected>>", preload)

window.mainloop()